### ISSUE TITLE
Upgrade to API v2

### ISSUE THREAD

**Issue by tsamaya** [meggsimum/w3w-java-wrapper#14]
Hi Christian,

This repo's what3words API wrapper is currently using v1 of the what3words API. This version was deprecated on 1/6/16 and will be switched off on 30/11/16.

This is just a heads up that this is coming up; please see https://docs.what3words.com/api/v1/#version for more information.

**Comment by chrismayer** [comment]
Hi Arnaud,

this must be some kind of telepathy :wink:. 

I did the upgrade these days and just opened a PR #15. Could you have a look at the PR? TIA!

**Comment by tsamaya** [comment]
Hi Christian,  
With pleasure, I will have a look at it.
Arnaud

**Comment by tsamaya** [comment]
Hi Christian,
great job. You should merge it.

**Comment by chrismayer** [comment]
Thanks @tsamaya for reviewing this. I just merged the PR #15.
